/**
 * THIRD-PARTY-NOTICES.md — the attribution the bundled open-source code
 * requires, regenerated from what is actually installed.
 *
 *   npm run licenses
 *
 * This exists because LICENSE stopped being Expo's. The app ships React
 * Native, Expo and their dependency tree inside the APK, and MIT/BSD/Apache
 * all require their notice to travel with the binary — a proprietary LICENSE
 * covers this repo's own work and says nothing on their behalf.
 *
 * The production tree as the lockfile marks it, which is a superset of what
 * the APK actually bundles — Babel and Metro are build-time deps of `expo`
 * and the lockfile has no flag saying so. Deliberately the superset: over-
 * attributing costs a longer file, under-attributing is a licence breach.
 *
 * Identical licence texts are printed once with every package that shares
 * them listed above — an unabridged per-package dump is the same MIT text
 * four hundred times, which is a file nobody can check rather than a fuller
 * one.
 *
 * It also writes the *published* copy — `notices/index.html` in the sibling
 * `spotter-legal` repo — because a notice living only in a private repository
 * has not travelled with anything. One pass writes both, so the page and the
 * file cannot describe different dependency trees. See the bottom of this
 * file, and `expo.extra.noticesUrl` in `app.json` for the link the app draws.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const log = (m) => console.log(`[licenses] ${m}`);

const lockPath = path.join(repoRoot, 'package-lock.json');
if (!existsSync(lockPath)) {
  log('no package-lock.json — run npm install first');
  process.exit(1);
}
const lock = JSON.parse(readFileSync(lockPath, 'utf8'));

/* — the production tree, as the lockfile records it — */

// Deduped by name@version: a package hoisted twice is one package, and the
// lockfile lists each nested copy under its own path.
const seen = new Set();
const prod = Object.entries(lock.packages ?? {})
  .filter(([dir, meta]) => dir.startsWith('node_modules/') && !meta.dev && !meta.link)
  .map(([dir, meta]) => ({ dir, name: dir.slice(dir.lastIndexOf('node_modules/') + 13), version: meta.version }))
  .filter((p) => {
    const id = `${p.name}@${p.version}`;
    if (seen.has(id)) return false;
    seen.add(id);
    return true;
  })
  .sort((a, b) => a.name.localeCompare(b.name) || String(a.version).localeCompare(String(b.version)));

/* — each package's declared licence and, where it ships one, its text — */

const LICENCE_FILE = /^(LICEN[CS]E|COPYING|NOTICE)(\.(md|txt))?$/i;

const readLicence = (dir) => {
  const abs = path.join(repoRoot, dir);
  if (!existsSync(abs)) return null;
  const hit = readdirSync(abs).find((f) => LICENCE_FILE.test(f));
  if (!hit) return null;
  try {
    return readFileSync(path.join(abs, hit), 'utf8').replace(/\r\n/g, '\n').trim();
  } catch {
    return null;
  }
};

const declared = (dir) => {
  const pj = path.join(repoRoot, dir, 'package.json');
  if (!existsSync(pj)) return 'UNKNOWN';
  try {
    const m = JSON.parse(readFileSync(pj, 'utf8'));
    if (typeof m.license === 'string') return m.license;
    if (m.license?.type) return m.license.type;
    if (Array.isArray(m.licenses)) return m.licenses.map((l) => l.type ?? l).join(' OR ');
  } catch {}
  return 'UNKNOWN';
};

/** text hash → { text, packages[] }; packages with no shipped text are listed apart. */
const texts = new Map();
const untexted = [];
let counted = 0;

for (const p of prod) {
  const id = `${p.name}@${p.version}`;
  const licence = declared(p.dir);
  const text = readLicence(p.dir);
  counted++;
  if (!text) {
    untexted.push({ id, licence });
    continue;
  }
  const key = createHash('sha1').update(text).digest('hex');
  if (!texts.has(key)) texts.set(key, { text, packages: [] });
  texts.get(key).packages.push({ id, licence });
}

/* — the file — */

const blocks = [...texts.values()].sort((a, b) => b.packages.length - a.packages.length);

const out = [
  '# Third-party notices',
  '',
  'Spotter is distributed with the open-source components listed below. Each is',
  'licensed by its own authors under its own terms, reproduced here as those',
  "terms require. Nothing in this file affects Spotter's own licence (LICENSE).",
  '',
  `Generated by \`npm run licenses\` from ${counted} production dependencies.`,
  'Regenerate it whenever dependencies change.',
  '',
  '---',
  '',
];

blocks.forEach((b, i) => {
  const kinds = [...new Set(b.packages.map((p) => p.licence))].join(', ');
  const n = b.packages.length;
  out.push(`## ${i + 1}. ${kinds} — ${n} package${n === 1 ? '' : 's'}`, '');
  out.push(...b.packages.map((p) => `- ${p.id}`), '', '```', b.text, '```', '');
});

if (untexted.length) {
  out.push(
    '## Packages shipping no licence file',
    '',
    'These declare a licence in their `package.json` without including its text.',
    'The declared identifier names the standard terms that apply.',
    '',
    ...untexted.map((p) => `- ${p.id} — ${p.licence}`),
    '',
  );
}

const file = path.join(repoRoot, 'THIRD-PARTY-NOTICES.md');
writeFileSync(file, out.join('\n'));
log(`${counted} packages, ${blocks.length} distinct licence texts → THIRD-PARTY-NOTICES.md`);

/* — the published page — */

/**
 * The same notices as a page, into the sibling `spotter-legal` repo.
 *
 * This file is the attribution MIT/BSD/Apache actually require, and a notice
 * that never leaves a private repository has not accompanied anything. The app
 * links `expo.extra.noticesUrl` from Settings → About; this is what has to be
 * standing at the other end of it.
 *
 * Emitted from here rather than written by hand over there for the reason the
 * markdown is generated at all: the text has to be what is *installed*, and
 * this is the one command that knows. A missing sibling is not an error — the
 * app repo has to build on a machine that never cloned the pages.
 */
const pagesDir = process.env.SPOTTER_LEGAL
  ? path.resolve(process.env.SPOTTER_LEGAL)
  : path.join(repoRoot, '..', 'spotter-legal');

if (!existsSync(pagesDir)) {
  log(`no spotter-legal beside the repo — page not written (looked in ${pagesDir})`);
} else {
  const esc = (s) =>
    String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  // Written out rather than taken from a locale: the pages are hand-dated in
  // this form ("22 August 2026") and a second format would read as a second
  // document. Machine-generated, so it is the day the list was taken.
  const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];
  const now = new Date();
  const stamp = `${now.getDate()} ${MONTHS[now.getMonth()]} ${now.getFullYear()}`;

  const sections = blocks.map((b, i) => {
    const kinds = [...new Set(b.packages.map((p) => p.licence))].join(', ');
    const n = b.packages.length;
    return [
      `<h2 id="l${i + 1}">${i + 1}. ${esc(kinds)} — ${n} package${n === 1 ? '' : 's'}</h2>`,
      '<ul class="pkgs">',
      ...b.packages.map((p) => `<li>${esc(p.id)}</li>`),
      '</ul>',
      `<pre>${esc(b.text)}</pre>`,
    ].join('\n');
  });

  const tail = untexted.length
    ? [
        '<h2 id="notext">Packages shipping no licence file</h2>',
        '<p>These declare a licence in their <code>package.json</code> without including',
        'its text. The declared identifier names the standard terms that apply.</p>',
        '<ul class="pkgs">',
        ...untexted.map((p) => `<li>${esc(p.id)} — ${esc(p.licence)}</li>`),
        '</ul>',
      ].join('\n')
    : '';

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Spotter — Open Source Licences</title>
<meta name="description" content="Attribution for the open-source components distributed with Spotter.">
<link rel="stylesheet" href="../style.css">
</head>
<body>
<!--
  Generated by \`npm run licenses\` in the Spotter repo. Do not edit by hand —
  the next regeneration overwrites it, and a hand-edited notice is attribution
  for something other than what ships.
-->

<header>
  <h1>Open Source Licences</h1>
  <p class="lede">Spotter, the Android application.</p>
  <p class="meta">Generated ${stamp} · <a href="../">Back</a></p>
</header>

<main>

  <p>Spotter is distributed with the open-source components listed below. Each is
    licensed by its own authors under its own terms, reproduced here as those terms
    require. Nothing on this page affects Spotter's own licence, and none of it
    applies to Spotter's own source.</p>

  <p class="meta">${counted} production dependencies · ${blocks.length} distinct licence texts.
    Regenerated whenever the app's dependencies change.</p>

${sections.join('\n\n')}

${tail}
</main>

<footer>
  <p>Spotter is made by Calvin Kohl. This page loads no fonts, scripts, cookies or assets from anywhere else.</p>
</footer>

</body>
</html>
`;

  mkdirSync(path.join(pagesDir, 'notices'), { recursive: true });
  writeFileSync(path.join(pagesDir, 'notices', 'index.html'), html);
  log(`→ ${path.join(pagesDir, 'notices', 'index.html')}`);
}

const unknown = [...blocks.flatMap((b) => b.packages), ...untexted].filter((p) => p.licence === 'UNKNOWN');
if (unknown.length) log(`note: ${unknown.length} package(s) declare no licence — check them: ${unknown.slice(0, 5).map((p) => p.id).join(', ')}`);
