/**
 * THIRD-PARTY-NOTICES.md — the attribution the bundled open-source code
 * requires, regenerated from what is actually installed.
 *
 *   npm run licenses
 *
 * This exists because LICENSE stopped being Expo's. The app ships React
 * Native, Expo and their dependency tree inside the APK, and MIT/BSD/Apache
 * all require their notice to travel with the binary — a proprietary LICENSE
 * covers this repo's own work and says nothing on their behalf.
 *
 * The production tree as the lockfile marks it, which is a superset of what
 * the APK actually bundles — Babel and Metro are build-time deps of `expo`
 * and the lockfile has no flag saying so. Deliberately the superset: over-
 * attributing costs a longer file, under-attributing is a licence breach.
 *
 * Identical licence texts are printed once with every package that shares
 * them listed above — an unabridged per-package dump is the same MIT text
 * four hundred times, which is a file nobody can check rather than a fuller
 * one.
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const log = (m) => console.log(`[licenses] ${m}`);

const lockPath = path.join(repoRoot, 'package-lock.json');
if (!existsSync(lockPath)) {
  log('no package-lock.json — run npm install first');
  process.exit(1);
}
const lock = JSON.parse(readFileSync(lockPath, 'utf8'));

/* — the production tree, as the lockfile records it — */

// Deduped by name@version: a package hoisted twice is one package, and the
// lockfile lists each nested copy under its own path.
const seen = new Set();
const prod = Object.entries(lock.packages ?? {})
  .filter(([dir, meta]) => dir.startsWith('node_modules/') && !meta.dev && !meta.link)
  .map(([dir, meta]) => ({ dir, name: dir.slice(dir.lastIndexOf('node_modules/') + 13), version: meta.version }))
  .filter((p) => {
    const id = `${p.name}@${p.version}`;
    if (seen.has(id)) return false;
    seen.add(id);
    return true;
  })
  .sort((a, b) => a.name.localeCompare(b.name) || String(a.version).localeCompare(String(b.version)));

/* — each package's declared licence and, where it ships one, its text — */

const LICENCE_FILE = /^(LICEN[CS]E|COPYING|NOTICE)(\.(md|txt))?$/i;

const readLicence = (dir) => {
  const abs = path.join(repoRoot, dir);
  if (!existsSync(abs)) return null;
  const hit = readdirSync(abs).find((f) => LICENCE_FILE.test(f));
  if (!hit) return null;
  try {
    return readFileSync(path.join(abs, hit), 'utf8').replace(/\r\n/g, '\n').trim();
  } catch {
    return null;
  }
};

const declared = (dir) => {
  const pj = path.join(repoRoot, dir, 'package.json');
  if (!existsSync(pj)) return 'UNKNOWN';
  try {
    const m = JSON.parse(readFileSync(pj, 'utf8'));
    if (typeof m.license === 'string') return m.license;
    if (m.license?.type) return m.license.type;
    if (Array.isArray(m.licenses)) return m.licenses.map((l) => l.type ?? l).join(' OR ');
  } catch {}
  return 'UNKNOWN';
};

/** text hash → { text, packages[] }; packages with no shipped text are listed apart. */
const texts = new Map();
const untexted = [];
let counted = 0;

for (const p of prod) {
  const id = `${p.name}@${p.version}`;
  const licence = declared(p.dir);
  const text = readLicence(p.dir);
  counted++;
  if (!text) {
    untexted.push({ id, licence });
    continue;
  }
  const key = createHash('sha1').update(text).digest('hex');
  if (!texts.has(key)) texts.set(key, { text, packages: [] });
  texts.get(key).packages.push({ id, licence });
}

/* — the file — */

const blocks = [...texts.values()].sort((a, b) => b.packages.length - a.packages.length);

const out = [
  '# Third-party notices',
  '',
  'Spotter is distributed with the open-source components listed below. Each is',
  'licensed by its own authors under its own terms, reproduced here as those',
  "terms require. Nothing in this file affects Spotter's own licence (LICENSE).",
  '',
  `Generated by \`npm run licenses\` from ${counted} production dependencies.`,
  'Regenerate it whenever dependencies change.',
  '',
  '---',
  '',
];

blocks.forEach((b, i) => {
  const kinds = [...new Set(b.packages.map((p) => p.licence))].join(', ');
  const n = b.packages.length;
  out.push(`## ${i + 1}. ${kinds} — ${n} package${n === 1 ? '' : 's'}`, '');
  out.push(...b.packages.map((p) => `- ${p.id}`), '', '```', b.text, '```', '');
});

if (untexted.length) {
  out.push(
    '## Packages shipping no licence file',
    '',
    'These declare a licence in their `package.json` without including its text.',
    'The declared identifier names the standard terms that apply.',
    '',
    ...untexted.map((p) => `- ${p.id} — ${p.licence}`),
    '',
  );
}

const file = path.join(repoRoot, 'THIRD-PARTY-NOTICES.md');
writeFileSync(file, out.join('\n'));
log(`${counted} packages, ${blocks.length} distinct licence texts → THIRD-PARTY-NOTICES.md`);

const unknown = [...blocks.flatMap((b) => b.packages), ...untexted].filter((p) => p.licence === 'UNKNOWN');
if (unknown.length) log(`note: ${unknown.length} package(s) declare no licence — check them: ${unknown.slice(0, 5).map((p) => p.id).join(', ')}`);
